// L^ (lhat) -- the copy-and-patch JIT: what the stencils and the runtime that
// lays them out agree on.
//
// A stencil is one instruction's work, written in C (stencils.c), compiled by
// Clang ahead of time and kept as bytes (gen_stencils.py writes them into
// stencils_<target>.h). Laying out a chunk is copying the stencils of its
// instructions one after another and writing the holes each one left:
// operands, constants, where to go next.
//
// Everything a stencil touches lives where the interpreter keeps it -- the
// frame's slots, payloads and tags apart (03 の 2.2) -- so leaving compiled
// code for the interpreter at any instruction costs nothing: a stencil that
// meets what it was not written for answers that instruction's pc, and the
// interpreter runs it from there. Nothing is held in a machine register
// across instructions.
//
// The contract is this file and include/lhat/value.h, nothing else: the
// generated bytes are committed, so a change to Machine must not move them.

#ifndef LHAT_JIT_H
#define LHAT_JIT_H

#include <stdbool.h>
#include <stdint.h>

#include "lhat/value.h"

// What a stencil asks of the machine, at a jump back -- the two questions
// the interpreter's slice poll asks (02 § 15.15 and the traps word).
typedef struct LhatJitPoll {
    int64_t *steps_left;
    const bool *traps;
} LhatJitPoll;

// The holes a stencil may leave, by the name of the symbol it refers to.
// gen_stencils.py reads the names; jit.c writes the values.
typedef enum {
    LHAT_JIT_HOLE_A,         // register operand A
    LHAT_JIT_HOLE_B,         // register operand B
    LHAT_JIT_HOLE_C,         // register operand C
    LHAT_JIT_HOLE_K,         // a constant's payload, as its 64 bits
    LHAT_JIT_HOLE_KTAG,      // a constant's tag
    LHAT_JIT_HOLE_PC,        // this instruction's pc, answered on leaving
    LHAT_JIT_HOLE_CONTINUE,  // the code of the instruction that follows
    LHAT_JIT_HOLE_TARGET,    // the code of the instruction jumped to
    LHAT_JIT_HOLE_COUNT
} LhatJitHoleKind;

// One hole: eight bytes at `offset` get the value of `kind` plus `addend`.
typedef struct {
    uint16_t offset;
    uint8_t kind;
    int32_t addend;
} LhatJitHole;

// One stencil as gen_stencils.py wrote it. `tail` is where the jump to the
// next instruction's code starts when that jump is the last thing in the
// stencil -- cut there when the next code is laid right after, so the one
// falls into the other. Equal to `size` when there is no such jump.
typedef struct {
    const uint8_t *code;
    uint16_t size;
    uint16_t tail;
    const LhatJitHole *holes;
    uint8_t hole_count;
} LhatJitStencil;

#if defined(LHAT_JIT_STENCIL_SOURCE) || defined(LHAT_WITH_JIT)
// Every stencil is one of these. preserve_none puts the three arguments in
// registers the stencils hand on untouched, and lets a stencil use every
// other register without saving it: nothing lives across a stencil.
#define LHAT_JIT_CC __attribute__((preserve_none))
typedef LHAT_JIT_CC uintptr_t LhatJitOp(LhatValueUnion *values,
                                         uint8_t *tags, LhatJitPoll *poll);
// The way in, in the ordinary convention: a host compiled by MSVC cannot
// call a preserve_none function, so this is a stencil too.
typedef uintptr_t LhatJitTrampoline(LhatValueUnion *values, uint8_t *tags,
                                    LhatJitPoll *poll, LhatJitOp *entry);
#endif

#ifdef LHAT_WITH_JIT
#include <stddef.h>

struct LhatChunk;
struct LhatMachine;

// Runs the chunk's compiled code from `pc`, laying the chunk out first if
// it has not been. Answers the pc the interpreter goes on from -- `pc`
// itself when there is nothing compiled to enter there.
size_t lhat_jit_run(struct LhatMachine *m, const struct LhatChunk *chunk,
                    size_t rbase, size_t pc);

// What lhat_chunk_dispose calls for the code a chunk carries.
void lhat_jit_free(void *code);
#endif

#endif
