// L^ (lhat) -- the copy-and-patch JIT: what the stencils and the runtime that
// lays them out agree on.
//
// A stencil is one instruction's work, written in C (stencils.c), compiled by
// Clang ahead of time and kept as bytes (gen_stencils.py writes them into
// stencils_<target>.h). Laying out a chunk is copying the stencils of its
// instructions one after another and writing the holes each one left:
// operands, constants, where to go next.
//
// Everything a stencil touches lives where the interpreter keeps it -- the
// frame's slots, payloads and tags apart (03 の 2.2) -- so leaving compiled
// code for the interpreter at any instruction costs nothing: a stencil that
// meets what it was not written for answers that instruction's pc, and the
// interpreter runs it from there. Nothing is held in a machine register
// across instructions.
//
// The contract is this file and the public include/lhat/value.h and
// object.h, nothing else: the generated bytes are committed, so a change to
// Machine must not move them, and a change to a public layout means running
// gen_stencils.py again (its --check says when).

#ifndef LHAT_JIT_H
#define LHAT_JIT_H

#include <stdbool.h>
#include <stdint.h>

#include "lhat/value.h"

// What the code runs against, beside the frame's slots. `steps_left` and
// `traps` are the two questions the interpreter's slice poll asks at a jump
// back (02 § 15.15 and the traps word). A call or a return made in the code
// moves to another frame: the helper that made it (jit.c) writes that
// frame's slots and closure here, and the stencil goes on with them. When
// it cannot go on in compiled code it writes `leave_pc` instead -- the pc
// the interpreter takes up, in whichever frame is on top by then.
typedef struct LhatJitContext {
    int64_t *steps_left;
    const bool *traps;
    struct LhatMachine *machine;
    LhatValueUnion *values;
    uint8_t *tags;
    const void *closure;
    uintptr_t leave_pc;
    bool moved;  // a helper changed the frame on top
} LhatJitContext;

// The holes a stencil may leave, by the name of the symbol it refers to.
// gen_stencils.py reads the names; jit.c writes the values.
typedef enum {
    LHAT_JIT_HOLE_A,         // register operand A
    LHAT_JIT_HOLE_B,         // register operand B
    LHAT_JIT_HOLE_C,         // register operand C
    LHAT_JIT_HOLE_K,         // a constant's payload, as its 64 bits
    LHAT_JIT_HOLE_KTAG,      // a constant's tag
    LHAT_JIT_HOLE_PC,        // this instruction's pc, answered on leaving
    LHAT_JIT_HOLE_CONTINUE,  // the code of the instruction that follows
    LHAT_JIT_HOLE_TARGET,    // the code of the instruction jumped to
    LHAT_JIT_HOLE_CALL,      // jit.c's call helper
    LHAT_JIT_HOLE_RETURN,    // jit.c's return helper
    LHAT_JIT_HOLE_STEP,      // the LhatJitStep this instruction takes
    LHAT_JIT_HOLE_COUNT
} LhatJitHoleKind;

// One hole: eight bytes at `offset` get the value of `kind` plus `addend`.
typedef struct {
    uint16_t offset;
    uint8_t kind;
    int32_t addend;
} LhatJitHole;

// One stencil as gen_stencils.py wrote it. `tail` is where the jump to the
// next instruction's code starts when that jump is the last thing in the
// stencil -- cut there when the next code is laid right after, so the one
// falls into the other. Equal to `size` when there is no such jump.
typedef struct {
    const uint8_t *code;
    uint16_t size;
    uint16_t tail;
    const LhatJitHole *holes;
    uint8_t hole_count;
} LhatJitStencil;

// Every stencil is one of these, in the platform's ordinary convention: the
// three arguments arrive in registers the stencils hand on untouched, and
// a stencil's work fits in the registers the convention lets it clobber, so
// none saves anything -- which makes the code enterable by a plain call,
// from any compiler, at the price of nothing.
typedef uintptr_t LhatJitOp(LhatValueUnion *values, uint8_t *tags,
                            LhatJitContext *context);

// A call or a return the code hands to C: done, it answers the code to go
// on with (context->values and ->tags say where); refused or done with no
// code to go on in, it answers NULL and context->leave_pc says where the
// interpreter takes up. `a`, `b`, `c` are the instruction's operands and
// `pc` is where it stands.
typedef LhatJitOp *LhatJitHelper(LhatJitContext *context, uintptr_t a,
                                 uintptr_t b, uintptr_t c, uintptr_t pc);

// One instruction's work handed to C without moving any frame: true when it
// was done, false when it was left untouched for the interpreter.
typedef bool LhatJitStep(LhatJitContext *context, uintptr_t a, uintptr_t b,
                         uintptr_t c);

#ifdef LHAT_WITH_JIT
#include <stddef.h>

struct LhatChunk;
struct LhatMachine;

// What a chunk's `jit` points at begins with this, so the interpreter can
// ask whether there is code to enter at a pc without calling anything:
// `enter` is NULL for a chunk that will not be laid out (or with the JIT
// turned off), and otherwise true where code of an instruction's own
// begins. A chunk not laid out yet has a NULL `jit` and is asked by
// calling lhat_jit_run, which lays it out.
typedef struct {
    const bool *enter;
} LhatJitCodeHead;

static inline bool lhat_jit_may_enter(const void *jit, size_t pc)
{
    const LhatJitCodeHead *head = (const LhatJitCodeHead *)jit;
    return head == NULL || (head->enter != NULL && head->enter[pc]);
}

// Set in what lhat_jit_run answers when a call or a return made in the
// code changed which frame is on top -- the interpreter reads it again only
// then.
#define LHAT_JIT_MOVED ((size_t)1 << (sizeof(size_t) * 8 - 1))

// Runs the chunk's compiled code from `pc`, laying the chunk out first if
// it has not been. Answers the pc the interpreter goes on from -- `pc`
// itself when there is nothing compiled to enter there -- in the frame on
// top of the machine, with LHAT_JIT_MOVED or'd in when that frame changed.
size_t lhat_jit_run(struct LhatMachine *m, const struct LhatChunk *chunk,
                    size_t rbase, size_t pc);

// What lhat_chunk_dispose calls for the code a chunk carries.
void lhat_jit_free(void *code);
#endif

#endif
