// L^ (lhat) -- the whole of what a host names.
//
// One header over the few in lhat/, which are the whole of the public
// surface: a host puts include/ on its path, writes
//
//     #include "lhat.h"
//
// and has the language. What is not here is not a host's business -- the
// tree, the checker's types, the instruction set and the collector all live
// in src/ and ship nowhere (05 の 8.7, and 02 の 14.17改2's build that runs
// bytecode with no front end at all).
//
// This is the header for running a program. There is one other, not reached
// from here: lhat/lexer.h, for reading one. A host colouring a script editor
// has to know where a word begins and ends, and 01 の 2.3's hat, 6.2's nested
// comments and 5.2's doubled quotes put that out of reach of anything but the
// lexer itself (07 の 4 章). Named by whoever wants it, so that a host which
// only runs bytecode carries none of it.
//
// The order a host works in is 05 の 8.7 and 5.3:
//
//     LhatProgram *program = lhat_program_new(true, lhat_load_file, NULL);
//     lhat_register_func(program, "system.io", "print", "p^string^;", fn, ctx);
//
//     const LhatUnit *root = lhat_program_check(program, "main.lh");
//     LhatMachine *machine =
//         lhat_program_compile(program) ? lhat_machine_new() : NULL;
//     lhat_program_install(program, machine);   // only with registrations
//     LhatRunResult ran = lhat_run(machine, lhat_unit_proto(root));
//
//     lhat_machine_dispose(machine);
//     lhat_program_free(program);
//
// LhatProgram is opaque and lhat_program_new is the only way to have one, so
// it is a pointer the host owns. The body of a unit is reached through
// lhat_unit_proto(root), not through anything on the program: a machine is
// given nothing (05 の 5.3), and what it runs is the one unit check named.
//
// Registering comes before checking, because the checker has to know what a
// signature says. Installing comes before running, because that is when what
// was registered reaches L^.modules -- a host that registered nothing may
// leave it out, as cli/main.c does.
//
// The machine is made after compiling only because nothing needs it earlier;
// lhat_machine_new() takes no arguments and may be called whenever.
//
// When a unit's text changes under machines already running -- an editor's
// save -- the whole of 05 の 5.7 is one call:
//
//     lhat_reload(program, "lib.lh", machines, machine_count);
//
// It invalidates, forgets the unit on each machine, rechecks, recompiles,
// and frees the retired bodies only once it has seen that no machine still
// holds a closure of one. The parts stay public for a host that wants the
// timing in its own hands.

#ifndef LHAT_H
#define LHAT_H

// The version, and the build knobs a consumer has to agree with the
// library on (generated by CMake).
#include "lhat/version.h"

// One shape for what every stage reports (03 の 1.1).
#include "lhat/error.h"

// What the language asks of its surroundings: where memory comes from, and
// how a unit's text is read (05 の 8.9).
#include "lhat/port.h"

// The unit graph, and what a host registers into it (05 の 5 章, 8.7, 8.8).
#include "lhat/program.h"

// What a compile answers with (03 の 5.3), and the machine that runs it.
#include "lhat/module.h"
#include "lhat/vm.h"

// What a debugger asks of the machine (09 章).
#include "lhat/debug.h"

#endif  // LHAT_H
