// L^ (lhat) -- the whole of what a host names.
//
// One header over the few in lhat/, which are the whole of the public
// surface: a host puts include/ on its path, writes
//
//     #include "lhat.h"
//
// and has the language. What is not here is not a host's business -- the
// tree, the checker's types, the instruction set and the collector all live
// in src/ and ship nowhere (05 の 8.7, and 02 の 14.17改2's build that runs
// bytecode with no front end at all).
//
// This is the header for running a program. There is one other, not reached
// from here: lhat/lexer.h, for reading one. A host colouring a script editor
// has to know where a word begins and ends, and 01 の 2.3's hat, 6.2's nested
// comments and 5.2's doubled quotes put that out of reach of anything but the
// lexer itself (07 の 4 章). Named by whoever wants it, so that a host which
// only runs bytecode carries none of it.
//
// The order a host works in is 05 の 8.7 and 5.3:
//
//     LhatProgram program;
//     lhat_program_init(&program, true, lhat_load_file, NULL);
//     lhat_register_func(&program, "system.io", "print", "p^string^;", fn, ctx);
//
//     const LhatUnit *root = lhat_program_check(&program, "main.lh");
//     size_t count = 0;
//     const LhatModule *modules = lhat_program_compile(&program, &count);
//
//     LhatMachine *machine = lhat_machine_new();
//     lhat_machine_set_modules(machine, modules, count);
//     lhat_program_install(&program, machine);   // only with registrations
//     lhat_run(machine, modules[root->index].proto);
//
// Registering comes before checking, because the checker has to know what a
// signature says. Installing comes before running, because that is when what
// was registered reaches L^.modules -- a host that registered nothing may
// leave it out, as cli/main.c does.
//
// The machine is made after compiling only because nothing needs it earlier;
// lhat_machine_new() takes no arguments and may be called whenever.

#ifndef LHAT_H
#define LHAT_H

// The version, and the build knobs a consumer has to agree with the
// library on (generated by CMake).
#include "lhat/version.h"

// One shape for what every stage reports (03 の 1.1).
#include "lhat/error.h"

// What the language asks of its surroundings: where memory comes from, and
// how a unit's text is read (05 の 8.9).
#include "lhat/port.h"

// The unit graph, and what a host registers into it (05 の 5 章, 8.7, 8.8).
#include "lhat/program.h"

// What a compile answers with (03 の 5.3), and the machine that runs it.
#include "lhat/module.h"
#include "lhat/vm.h"

#endif  // LHAT_H
